### ISSUE TITLE
io2014codelabs Website is just blank on Opera12.16

### ISSUE THREAD

**Issue by DavidWiesner** [googlesamples/io2014-codelabs#1]
At first, i will say thanks for this cool Project!

I want to visit your appspot Website 
http://io2014codelabs.appspot.com/static/codelabs/android-actions/
But it just shows a blank page on my Browser. 
![screenshot 2014-06-27 12 16 58](https://cloud.githubusercontent.com/assets/243115/3410320/609d5124-fde5-11e3-9e03-a97da184bd18.png)

Firefox and Chromium just works fine its just Opera 12.16 that throws this JavaScript Exception:

```
Uncaught exception: TypeError: Cannot convert 'a' to object
Error thrown at line 12, column 48550 in r(a, b, c) in http://io2014codelabs.appspot.com/static/bower_components/platform/platform.js:
    var d=a.prototype;
called from line 13, column 37026 in <anonymous function>(a) in http://io2014codelabs.appspot.com/static/bower_components/platform/platform.js:
    b.prototype=Object.create(d.prototype),f(b.prototype,{get textContent(){return this.data},set textContent(a){this.data=a},get data(){return this.impl.data},set data(a){var b=this.impl.data;e(this,"characterData",{oldValue:b}),this.impl.data=a}}),f(b.prototype,c),g(h,b,document.createTextNode("")),a.wrappers.CharacterData=b
called from line 12, column 0 in http://io2014codelabs.appspot.com/static/bower_components/platform/platform.js:
```

regards,
David

**Comment by inl1ne** [comment]
The I/O codelabs website requires a browser with support for the latest open web standards.
