### ISSUE TITLE
polymer-build-mobile - Step 3 - using css attribute selectors needs explanation

### ISSUE THREAD

**Issue by mckoss** [googlesamples/io2014-codelabs#12]
http://io2014codelabs.appspot.com/static/codelabs/polymer-build-mobile/#3

Uses css selectors like [main] and [drawer].  In my experience, most CSS developers will not recognize these as attribute queries.  I think a little explanation of how these work, and what they are selecting would be in order.

**Comment by inl1ne** [comment]
Added internally as b/16374135
