### ISSUE TITLE
polymer-build-mobile - Step 8 - core-toolbar is more complex than shown

### ISSUE THREAD

**Issue by mckoss** [googlesamples/io2014-codelabs#15]
http://io2014codelabs.appspot.com/static/codelabs/polymer-build-mobile/#8

shows example of core-toolbar context being simple strings.  In fact, the code has nested other tags in it.

The sample code in the tutorial should probably just omit the <core-toolbar> content since this part is just suggesting changing the attributes of the tag.

Replace:

```
<core-header-panel drawer mode="waterfall">
  <core-toolbar class="{{ {tall : !narrow} | tokenList }}">Menu</core-toolbar>
   ...
 <core-header-panel main mode="waterfall">
     <core-toolbar class="{{ {tall : !narrow} | tokenList }}">My Notes</core-toolbar>
```

with 

```
<core-header-panel drawer mode="waterfall">
  <core-toolbar class="{{ {tall : !narrow} | tokenList }}">
   ...
 <core-header-panel main mode="waterfall">
     <core-toolbar class="{{ {tall : !narrow} | tokenList }}">
 ...
```

**Comment by inl1ne** [comment]
Added internally as b/16374131
