### ISSUE TITLE
The main README file is not about Google I/O nor code labs

### ISSUE THREAD

**Issue by campoy** [googlesamples/io2014-codelabs#18]
I'm not sure what kind of information we should expect here, but definitely not an example of Pub Sub Java.

**Comment by tjohns** [comment]
Oh, yikes. Thanks for catching that.

Merge commit 81f644b5110183daac38fda86d7f297d231feebe was accidently applied to the wrong project while we were setting up the automerger for another project.

I had to do a force-push to fix the history, but this should be fixed now.
