### ISSUE TITLE
Can Polymer Mobile example be deployed to mobile from CDE?

### ISSUE THREAD

**Issue by joannbrereton** [googlesamples/io2014-codelabs#4]
Feel free to delete or move this question if it is not in the right place.   I've been kicking the tires on CDE all weekend.   I've followed your Polymer Mobile example and while I can use the emulation mode to show the app, I haven't found a way to actually deploy the app to mobile.    Can you elucidate on that, either in the tutorial or here?

**Comment by mckoss** [comment]
You can use Chrome Dev Tools remote debugging to view the polymer app on a mobile device.

https://developer.chrome.com/devtools/docs/remote-debugging

Just go to chrome://inspect - and enable port forwarding (I found that you need to pick a lower numbered port for your mobile device (like 8000), than the port exposed by the CDE web server.
