### ISSUE TITLE
chromelab mobile game lab does not seem to run on iphone

### ISSUE THREAD

**Issue by fedex1** [googlesamples/io2014-codelabs#6]
I loaded the generic tic tac toe application from the lab with no modification here: http://property.brooklyncoop.org/static/test_codelab/index.html

It show a blank screen and does not play tic tac toe.  

Is this supposed to work or is it a known limitation?

Thanks.

**Comment by inl1ne** [comment]
Working as intended. Chrome Apps are a desktop-only feature.
