### ISSUE TITLE
polymer-build-mobile - Step 2 - Emphasize "replace" styles.css

### ISSUE THREAD

**Issue by mckoss** [googlesamples/io2014-codelabs#9]
" Open styles.css and replace its contents with this CSS rule:"

In practice, many people just append the rule to the end of the file.  It should be called out more forcibly that you should DELETE EVERY LINE OF THIS FILE AND THEN ADD THIS ONE RULE:

Otherwise, formatting is messed up for the rest of the code lab.

**Comment by inl1ne** [comment]
Added internally as b/16375611
